#!/bin/sh
echo 'bokker bok.bok.bokkety.bok'
echo $1
echo $2
echo $3
echo $4

curl -X POST --data-urlencode \
"payload={\"channel\": \"${3}\", \"username\": \"CaptainHook\", \"text\": \"Captain Hook has detected that the ${2} container has hit the open seas.\", \"icon_emoji\": \":whale:\"}" \
$1
